# SEE: https://github.com/tmuxinator/tmuxinator
name: application
root: /Users/andrew.mason/path/to/application

on_project_start: lsof -t -i tcp:3000 | xargs kill -KILL; lsof -t -i tcp:3035 | xargs kill -KILL;
pre_window: nvm use

windows:
  - shell: code .
  - server:
      layout: 3c9e,117x81,0,0[117x58,0,0,2,117x22,0,59{84x22,0,59,3,32x22,85,59,4}]
      panes:
        - bundle exec rails s -p 3000 -b lvh.me
        - bin/webpack-dev-server
        - redis-cli flushall && bundle exec sidekiq -C config/sidekiq.yml
  - console: bundle exec rails c
  - ngrok: ngrok http -subdomain=andrewmcodes 3000
